delete from pergunta;

Insert into pergunta(ID, PERGUNTA) values
 (1, 'Esforço-me para realizar as coisas que devem ser feitas'),
 (2, 'Quando me deparo com um problema difícil, levo muito tempo para encontrar a solução'),
 (3, 'Termino meu trabalho a tempo'),
 (4, 'Aborreçome quando as coisas não são feitas devidamente'),
 (5, 'Prefiro situações em que posso controlar ao máximo o resultado final'),
 (6, 'Gosto de pensar no futuro'),
 (7, 'Quando começo uma tarefa ou projeto novo, coleto todas as informações possíveis antes de dar prosseguimento a ele'),
 (8, 'Planejo um projeto grande dividindo-o em tarefas mais simples'),
 (9, 'Consigo que os outros apoiem minhas recomendações'),
 (10, 'Tenho confiança de que posso ser bem-sucedido em qualquer atividade que me proponho executar'),
 (11, 'Não importa com quem fale, sempre escuto atentamente'),
 (12, 'Faço as coisas que devem ser feitas sem que os outros tenham que me pedir'),
 (13, 'Insisto várias vezes para conseguir que as outras pessoas façam o que desejo'),
 (14, 'Sou fiel as promessas que faço'),
 (15, 'Meu rendimento no trabalho é melhor do que o das outras pessoas com quem trabalho'),
 (16, 'Envolvo-me com algo novo só depois de ter feito todo o possível para assegurar o seu êxito'),
 (17, 'Acho uma perda de tempo preocupar-me com o que farei da minha vida'),
 (18, 'Procuro conselhos das pessoas que são especialistas no ramo em que estou atuando'),
 (19, 'Considero cuidadosamente as vantagens e desvantagens de diferentes alternativas antes de realizar uma tarefa'),
 (20, 'Não perco muito tempo pensando em como posso influenciar as outras pessoas'),
 (21, 'Mudo a maneira de pensar se outros discordam energicamente dos meus pontos de vista'),
 (22, 'Aborreço-me quando não consigo o que quero'),
 (23, 'Gosto de desafios e novas oportunidades'),
 (24, 'Quando algo se interpõe ao que estou tentando fazer, persisto em minha tarefa'),
 (25, 'Se necessário, não me importo de fazer o trabalho dos outrospara cumprir um prazo de entrega'),
 (26, 'Aborreço-me quando perdo tempo'),
 (27, 'Considero minhas possibilidades de êxito ou fracasso antes de começar a atuar'),
 (28, 'Quanto mais especifico forem minhas expectativas em relação ao que obter na vida, maiores serão minhas posibilidades de êxito'),
 (29, 'Tomo decisões sem perder tempo, buscando informações'),
 (30, 'Procuro levar em conta todos os problemas que podem se apresentar'),
 (31, 'Conto com pessoas influentes para alcançar minhas metas'),
 (32, 'Quando estou executando algo difícil e desafiador, tenho confiança em meu sucesso'),
 (33, 'Tive fracassos no passado'),
 (34, 'Prefiro executar tarefas que domino perfeitamente e em que me sinto seguro'),
 (35, 'Quando me deparo com sérias dificuldades, rapidamente passo para outras atividades'),
 (36, 'Quando estou fazendo um trabalho para outra pessoa, me esforço, de forma especial, para que ela fique satisfeita com o trabalho'),
 (37, 'Nunca fico totalmente satisfeito com a forma com que são feitas as coisas; sempre considero que há uma maneira melhor de fazẽ-las'),
 (38, 'Executo tarefas arriscada'),
 (39, 'Conto com um plano claro de vida'),
 (40, 'Quando executado um projeto para alguém, faço muitas perguntas para assegurar-me de que entendi o que ela/ele quer'),
 (41, 'Enfrento os problemas à medida que surgem, em vez de perder tempo antecipando-os'),
 (42, 'Para alcançar minhas metas, procuro soluções que beneficiem todas as pessoas envolvidas em um problema'),
 (43, 'O trabalho que realizo é excelente'),
 (44, 'Em algumas ocasiões obtive vantagens de outras pessoas'),
 (45, 'Aventuro-me a fazer coisas novas e diferentes das que fiz no passado'),
 (46, 'Tenho diferentes maneiras de superar obstáculos que se apresentam para a obtenção de minha metas'),
 (47, 'Minha familia e minha vida pessoal são mais importante para mim do que as datas de entrega de trabalhos determinados por mim mesmo'),
 (48, 'Encontro a maneira mais rapida de terminar os trabalhos, tanto em casa quanto no trabalho'),
 (49, 'Faço coisas que as outras pessoas consideram arriscada'),
 (50, 'Preocupo-me tanto em alcançar minhas metas semanais quanto minhas metas anuais'),
 (51, 'Conto com varias fontos de informações ao  procurar ajuda para a execução de tarefas e projetos'),
 (52, 'Se determinado método para enfrentar um problema não der certo, recorro a outro'),
 (53, 'Posso conseguir que pessoas com firmes convicções e opiniões mudem seu modo de pensar'),
 (54, 'Mantenho-me firme em minhas decisões, mesmo quando as outras pessoas se opõem energicamente'),
 (55, 'Quando desconheço algo, não hesito em admiti-lo');

Insert into resposta(NOME) values ('João da Silva');

Insert into resposta_pergunta(PONTOS, PERGUNTA_ID, RESPOSTA_ID) values
 (3, 1, 1),
 (5, 2, 1);